version: '3.8'

services:
  mysql:
    container_name: mysql-container
    image: mysql:latest
    restart: always
    env_file: .env
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
    driver: bridge